version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
      - ollama_models:/root/.ollama
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - ollama

  frontend:
    image: nginx:alpine
    volumes:
      - ./web/html:/usr/share/nginx/html
      - ./web/css:/usr/share/nginx/html/css
      - ./web/js:/usr/share/nginx/html/js
      - ./resources:/usr/share/nginx/html/resources
    ports:
      - "8080:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    restart: unless-stopped
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama_models:
